# cloudbuild-api.yaml
steps:
  # 1. API 이미지 빌드
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/comic-api",
        "./comic-api"
      ]

  # 2. API 이미지 푸시
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/comic-api"
      ]

  # 3. Cloud Run 배포
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "comic-api",
        "--image",
        "gcr.io/$PROJECT_ID/comic-api",
        "--region",
        "asia-northeast3",
        "--platform",
        "managed",
        "--allow-unauthenticated"
      ]

images:
  - gcr.io/$PROJECT_ID/comic-api