create table public.comic_character (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id text not null,
  comics_id bigint not null,
  photo_id integer null,
  note character varying null,
  character_name character varying not null,
  photo_url text null,
  affinity bigint null default '1'::bigint,
  news_list text null,
  constraint comic_character_pkey primary key (id),
  constraint comic_character_comics_id_fkey foreign KEY (comics_id) references comics (id)
) TABLESPACE pg_default;

create table public.comics (
  id bigint generated by default as identity not null,
  title text null,
  author text null,
  review text null,
  rating integer null,
  "coverImage" text null,
  "createdAt" timestamp with time zone not null default timezone ('utc'::text, now()),
  user_id text null,
  constraint comics_pkey primary key (id)
) TABLESPACE pg_default;


create table public.photo_info (
  id integer not null,
  created_at timestamp with time zone not null default now(),
  photo_base64 character varying null,
  note character varying null,
  keyword1 text null,
  keyword2 text null,
  num integer not null,
  constraint photo_info_pkey primary key (id, num),
  constraint photo_info_id_fkey foreign KEY (id) references comic_character (id)
) TABLESPACE pg_default;